{% set name = "category_encoders" %}
{% set version = "2.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6e927c9681c68598980d2debed348c7ed39173c616ffe46936ac62c35086cbb4
    folder: dist
  - url: https://github.com/scikit-learn-contrib/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 5d365116843c1d06a18d75a38482af05726a88b5ecb519c845a02f14010bd216
    folder: src

build:
  noarch: python
  number: 0
  script:
    - cd dist && {{ PYTHON }} -m pip install -vvv .

requirements:
  host:
    - numpy >=1.14.0
    - pandas >=0.21.1
    - patsy >=0.5.1
    - pip
    - python >=3.5
    - scikit-learn >=0.20.0
    - scipy >=1.0.0
    - statsmodels >=0.9.0
  run:
    - numpy >=1.14.0
    - pandas >=0.21.1
    - patsy >=0.5.1
    - python >=3.5
    - scikit-learn >=0.20.0
    - scipy >=1.0.0
    - statsmodels >=0.9.0

test:
  source_files:
    - src/tests
  requires:
    - cython
    - pip
    - pytest
    - pytest-cov
  imports:
    - category_encoders
  commands:
    - python -m pip check
    - cd src && pytest -vv --cov category_encoders -k "not (pandas_index or truncated_index)"

about:
  home: https://github.com/scikit-learn-contrib/categorical_encoding
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE.md
  summary: A collection sklearn transformers to encode categorical variables as numeric
  doc_url: https://contrib.scikit-learn.org/categorical-encoding
  description: |-
    A set of scikit-learn-style transformers for encoding categorical variables
    into numeric with different techniques. While ordinal, one-hot, and hashing
    encoders have similar equivalents in the existing scikit-learn version, the
    transformers in this library all share a few useful properties:

    - First-class support for pandas dataframes as an input (and optionally as
      output)

    - Can explicitly configure which columns in the data are encoded by name or
      index, or infer non-numeric columns regardless of input type

    - Can drop any columns with very low variance based on training set
      optionally

    - Portability: train a transformer on data, pickle it, reuse it later and
      get the same thing out.

    - Full compatibility with sklearn pipelines, input an array-like dataset
      like any other transformer

extra:
  recipe-maintainers:
    - bollwyvl
    - nirajd
    - wdm0006
